<a href="https://colab.research.google.com/github/RajaSekhar1311/Data_Analyst_PW_Skills/blob/main/Numpy_Practical_Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1, 101, (3,3))

In [ ]:
arr

array([[11, 24, 20],
       [ 6,  2, 56],
       [35, 25, 46]])

In [ ]:
arr.T # interchange its Rows and Columns

array([[11,  6, 35],
       [24,  2, 25],
       [20, 56, 46]])

# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [ ]:
import numpy as np

arr = np.random.rand(4, 4)
print(arr)

# Add a border of zeros around the array
bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(bordered_arr)

[[0.15244274 0.89316036 0.58022445 0.53545148]
 [0.82337442 0.6933975  0.6707306  0.89261139]
 [0.74624177 0.92800204 0.02422843 0.81607346]
 [0.35904564 0.14493712 0.60739427 0.60097641]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.15244274 0.89316036 0.58022445 0.53545148 0.        ]
 [0.         0.82337442 0.6933975  0.6707306  0.89261139 0.        ]
 [0.         0.74624177 0.92800204 0.02422843 0.81607346 0.        ]
 [0.         0.35904564 0.14493712 0.60739427 0.60097641 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


# 4.Using NumPy, create an array of integers from 10 to 60 with a step of 5






In [ ]:
np.arange(10, 61, 5)


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [ ]:
arr = np.array(['python', 'numpy', 'pandas'])
arr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
np.char.upper(arr)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [ ]:
np.char.lower(arr)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
np.char.title(arr)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [ ]:
np.char.upper(arr[0])

array('PYTHON', dtype='<U6')

In [ ]:
np.char.upper(arr[:2])

array(['PYTHON', 'NUMPY'], dtype='<U6')

In [ ]:
np.char.lower(arr[:2])

array(['python', 'numpy'], dtype='<U6')

# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
arr = np.array(['hello', 'world', 'numpy'])
new_arr = np.array([ ' '.join(list(word)) for word in arr])
print(new_arr)

['h e l l o' 'w o r l d' 'n u m p y']


# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Element-wise addition
addition_result = arr1 + arr2
print("Addition:\n", addition_result)

# Element-wise subtraction
subtraction_result = arr1 - arr2
print("Subtraction:\n", subtraction_result)

# Element-wise multiplication
multiplication_result = arr1 * arr2
print("Multiplication:\n", multiplication_result)

# Element-wise division
division_result = arr1 / arr2
print("Division:\n", division_result)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


# 8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
identity_matrix = np.identity(5)
print("Identity Matrix:\n", identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("Diagonal Elements:\n", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
 [1. 1. 1. 1. 1.]


# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array



In [ ]:
def is_prime(n):

  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True

arr = np.random.randint(0, 1001, 100)
arr




array([916, 894, 997, 338, 587, 100, 366, 399, 792, 848, 377, 589, 163,
       951, 991, 201, 568, 127, 216, 121, 780, 928, 482, 663, 492, 287,
       313, 744, 606,  38,  87, 552, 589, 669, 834, 123, 603, 569, 622,
       304, 540, 458, 167, 209, 297, 597, 423, 952, 296, 547, 376, 252,
       243, 936, 967, 268, 552, 819, 540, 535, 543, 651, 319, 933, 176,
       379, 184, 287, 872, 787, 552, 590, 328, 410, 694, 732, 838, 683,
       398,  74, 865, 370, 265, 646, 449, 231, 588, 794, 420, 806, 106,
       518, 372, 490, 498, 277, 764,  26, 247, 148])

In [ ]:
prime_numbers = [num for num in arr if is_prime(num)]
print("Prime numbers in the array:", prime_numbers)

Prime numbers in the array: [997, 587, 163, 991, 127, 313, 569, 167, 547, 967, 379, 787, 683, 449, 277]


# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [ ]:
temperatures = np.random.randint(15, 35, 28)

# Reshape the array into a 4x7 matrix (4 weeks, 7 days each)
weekly_temperatures = temperatures.reshape(4, 7)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Daily Temperatures:\n", temperatures)
print("\nWeekly Temperatures:\n", weekly_temperatures)
print("\nWeekly Averages:\n", weekly_averages)



Daily Temperatures:
 [16 15 24 17 16 18 22 19 26 20 22 34 25 28 33 32 27 28 28 27 15 18 33 29
 18 30 31 33]

Weekly Temperatures:
 [[16 15 24 17 16 18 22]
 [19 26 20 22 34 25 28]
 [33 32 27 28 28 27 15]
 [18 33 29 18 30 31 33]]

Weekly Averages:
 [18.28571429 24.85714286 27.14285714 27.42857143]
